# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: [push]

    steps:
      - name: GitHub Action for pytest
        uses: cclauss/GitHub-Action-for-pytest@0.5.0

 
